export const REQUEST_DATA_STARTED = "REQUEST_DATA_STARTED";
export const REQUEST_DATA_FAILED = "REQUEST_DATA_FAILED";
export const CREATE_TWEET = "CREATE_TWEET";
export const CREATE_LIKE = "CREATE_LIKE";
export const CREATE_RETWEET = "CREATE_RETWEET";
export const CREATE_BOOKMARKS = "CREATE_BOOKMARKS";
export const CREATE_COMMET = "CREATE_COMMET";
export const DELETE_TWEET = "DELETE_TWEET";
export const DELETE_RETWEET = "DELETE_RETWEET";
export const COUNT_RETWEETS = "COUNT_RETWEET";
export const COUNT_LIKES = "COUNT_LIKES";
export const COUNT_COMMENTS = "COUNT_COMMENTS";

export const REQUEST_TRENDS_STARTED = "REQUEST_TRENDS_STARTED";
export const REQUEST_TRENDS_FAILED = "REQUEST_TRENDS_FAILED";
export const GET_TRENDS = "GET_TRENDS";
export const SET_TRENDS = "SET_TRENDS";
export const GET_TRENDS_FOR_AUTH_USER = "GET_TRENDS_FOR_AUTH_USER";
export const CREATE_NOT_INTERESTING_TREND = "CREATE_NOT_INTERESTING_TREND";
export const SET_NOT_INTERESTING_TREND = "SET_NOT_INTERESTING_TREND";

export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";
export const SET_AUTH = "SET_AUTH";
export const GET_AUTH = "GET_AUTH";
export const GET_USER_PROFILE_BY_ID = "GET_USER_PROFILE_BY_ID";
export const SET_USER_PROFILE_BY_ID = "SET_USER_PROFILE_BY_ID";
export const REGISTRATION = "REGISTRATION";
export const AUTHENTICATION = "AUTHENTICATION";

export const REQUEST_USER_PROFILE_STARTED = "REQUEST_USER_PROFILE_STARTED";
export const REQUEST_USER_PROFILE_FAILED = "REQUEST_USER_PROFILE__FAILED";
export const REQUEST_AUTHENTICATION_STARTED = "REQUEST_AUTHENTICATION_STARTED";
export const REQUEST_AUTHENTICATION_FAILED = "REQUEST_AUTHENTICATION_FAILED";
export const REQUEST_USER_PROFILE_BY_ID_STARTED =
  "REQUEST_PROFILE_BY_ID_STARTED";
export const REQUEST_USER_PROFILE_BY_ID_FAILED =
  "REQUEST_USER_PROFILE_BY_ID_FAILED";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const SET_USER_PROFILE = "SET_PROFILE";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_USERS_WHO_TO_FOLLOW = "GET_USERS_WHO_TO_FOLLOW";
export const SET_USERS_WHO_TO_FOLLOW = "SET_USERS_WHO_TO_FOLLOW";
export const GET_SEARCHED_USERS = "GET_SEARCHED_USERS";
export const SET_SEARCHED_USERS = "SET_SEARCHED_USERS";
export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const SET_FOLLOWERS = "SET_FOLLOWERS";
export const REQUEST_FOLLOWERS_STARTED = "REQUEST_FOLLOWERS_STARTED";
export const REQUEST_FOLLOWERS_FAILED = "REQUEST_FOLLOWERS_FAILED";

export const GET_FOLLOWINGS = "GET_FOLLOWINGS";
export const SET_FOLLOWINGS = "SET_FOLLOWINGS";
export const REQUEST_FOLLOWINGS_STARTED = "REQUEST_FOLLOWINGS_STARTED";
export const REQUEST_FOLLOWINGS_FAILED = "REQUEST_FOLLOWINGS_FAILED";

export const GET_LIST_WHO_NOT_READING = "GET_LIST_WHO_NOT_READING";
export const SET_LIST_WHO_NOT_READING = "SET_LIST_WHO_NOT_READING";
export const DELETE_USER_IN_LIST_WHO_NOT_READING =
  "DELETE_USER_IN_LIST_WHO_NOT_READING";
export const REQUEST_LIST_WHO_NOT_READING_STARTED =
  "REQUEST_LIST_WHO_NOT_READING_STARTED";
export const REQUEST_LIST_WHO_NOT_READING_FAILED =
  "REQUEST_LIST_WHO_NOT_READING_FAILED";

export const GET_PREVIEW_PROFILE = "GET_PREVIEW_PROFILE";
export const SET_PREVIEW_PROFILE = "SET_PREVIEW_PROFILE";
export const REQUEST_PREVIEW_PROFILE_STARTED = "REQUEST_DATA_STARTED";
export const REQUEST_PREVIEW_PROFILE_FAILED = "REQUEST_DATA_FAILED";

export const CREATE_FOLLOWING = "CREATE_FOLLOWING";
export const SET_NEW_FOLLOWING_IN_FOLLOWING_LIST =
  "SET_NEW_FOLLOWING_IN_FOLLOWING_LIST";
export const SET_NEW_FOLLOWING_IN_FOLLOWERS_LIST =
  "SET_NEW_FOLLOWING_IN_FOLLOWERS_LIST";
export const SET_FOLLOW_PREVIEW_PROFILE = "SET_FOLLOW_PREVIEW_PROFILE";
export const DELETE_FOLLOWING = "DELETE_FOLLOWING";
export const SET_DELETED_FOLLOW_IN_FOLLOWING_LIST =
  "SET_DELETED_FOLLOW_IN_FOLLOWING_LIST";
export const SET_DELETED_FOLLOW_IN_FOLLOWERS_LIST =
  "SET_DELETED_FOLLOW_IN_FOLLOWERS_LIST";

export const GET_MAIN_CONTENT = "GET_MAIN_CONTENT";
export const SET_MAIN_CONTENT = "SET_MAIN_CONTENT";
export const GET_MAIN_CONTENT_FOR_NOT_AUTH_USER =
  "GET_MAIN_CONTENT_FOR_NOT_AUTH_USER";
export const SET_MAIN_CONTENT_FOR_NOT_AUTH_USER =
  "SET_MAIN_CONTENT_FOR_NOT_AUTH_USER";

export const GET_VISIBILITY_BOOKMARKS = "GET_VISIBILITY_BOOKMARKS";
export const SET_VISIBILITY_BOOKMARKS = "SET_VISIBILITY_BOOKMARKS";

export const GET_VISIBILITY_TWEETS_FOR_AUTH_USER =
  "GET_VISIBILITY_TWEETS_FOR_AUTH_USERS";
export const SET_VISIBILITY_TWEETS_FOR_AUTH_USER =
  "SET_VISIBILITY_TWEETS_FOR_AUTH_USER";
export const GET_VISIBILITY_TWEETS_WHO_YOU_READ =
  "GET_VISIBILITY_TWEETS_WHO_YOU_READ";
export const SET_VISIBILITY_TWEETS_WHO_YOU_READ =
  "SET_VISIBILITY_TWEETS_FOR_AUTH_USER";
export const GET_VISIBILITY_TWEETS_BY_USER = "GET_VISIBILITY_TWEETS_BY_USER";
export const SET_VISIBILITY_TWEETS_BY_USER = "SET_VISIBILITY_TWEETS_BY_USER";
export const GET_VISIBILITY_TWEETS_WITH_LIKES =
  "GET_VISIBILITY_TWEETS_WITH_LIKES";
export const SET_VISIBILITY_TWEETS_WITH_LIKES =
  "SET_VISIBILITY_TWEETS_WITH_LIKES";
export const GET_VISIBILITY_TWEETS_WITH_MEDIA =
  "GET_VISIBILITY_TWEETS_WITH_MEDIA";
export const SET_VISIBILITY_TWEETS_WITH_MEDIA =
  "SET_VISIBILITY_TWEETS_WITH_MEDIA";
export const GET_VISIBILITY_ANSWERS = "GET_VISIBILITY_ANSWERS";
export const SET_VISIBILITY_ANSWERS = "SET_VISIBILITY_ANSWERS";
