export const SET_MAIN_CONTENT_FOR_NOT_AUTH_USER =
  "SET_MAIN_CONTENT_FOR_NOT_AUTH_USER";
export const SET_MAIN_CONTENT_FOR_AUTH_USER = "SET_MAIN_CONTENT_FOR_AUTH_USER";

export const GET_MAIN_CONTENT_FOR_NOT_AUTH_USER =
  "GET_MAIN_CONTENT_FOR_NOT_AUTH_USER";
export const GET_MAIN_CONTENT_FOR_AUTH_USER = "GET_MAIN_CONTENT";

export const REQUEST_CONTENT_FOR_NOT_AUTH_STARTED =
  "REQUEST_CONTENT_FOR_NOT_AUTH_STARTED";
export const REQUEST_CONTENT_FOR_NOT_AUTH_FAILED =
  "REQUEST_CONTENT_FOR_NOT_AUTH_FAILED";
export const REQUEST_CONTENT_FOR_AUTH_USER_STARTED =
  "REQUEST_CONTENT_FOR_AUTH_USER_STARTED";
export const REQUEST_CONTENT_FOR_AUTH_USER_FAILED =
  "REQUEST_CONTENT_FOR_AUTH_USER_FAILED";
