export const SET_NOT_INTERESTING_TREND = "SET_NOT_INTERESTING_TREND";
export const SET_TRENDS = "SET_TRENDS";

export const CREATE_NOT_INTERESTING_TREND = "CREATE_NOT_INTERESTING_TREND";

export const GET_TRENDS = "GET_TRENDS";
export const GET_TRENDS_FOR_AUTH_USER = "GET_TRENDS_FOR_AUTH_USER";

export const REQUEST_TRENDS_STARTED = "REQUEST_TRENDS_STARTED";
export const REQUEST_TRENDS_FAILED = "REQUEST_TRENDS_FAILED";
