export const SET_TWEETS = "SET_TWEETS";
export const SET_NEW_TWEET = "SET_NEW_TWEET";
export const SET_MORE_TWEETS = "SET_MORE_TWEETS";
export const SET_BOOKMARK = "SET_BOOKMARK";
export const SET_LIKE = "SET_LIKE";
export const SET_RETWEET = "SET_RETWEET";

export const UNSET_RETWEET = "UNSET_RETWEET";
export const DELETE_BOOKMARK = "DELETE_BOOKMARK";
export const DELETE_LIKE = "DELETE_LIKE";
export const UNSET_TWEET = "UNSET_TWEET";
export const CREATE_TWEET = "CREATE_TWEET";
export const CREATE_LIKE = "CREATE_LIKE";
export const CREATE_RETWEET = "CREATE_RETWEET";
export const CREATE_BOOKMARKS = "CREATE_BOOKMARKS";
export const CREATE_COMMET = "CREATE_COMMET";
export const DELETE_TWEET = "DELETE_TWEET";
export const DELETE_RETWEET = "DELETE_RETWEET";
export const COUNT_RETWEETS = "COUNT_RETWEET";
export const COUNT_LIKES = "COUNT_LIKES";
export const COUNT_COMMENTS = "COUNT_COMMENTS";

export const GET_TWEETS = "GET_TWEETS";
export const GET_MORE_TWEETS = "GET_MORE_TWEETS";
export const GET_MORE_USER_TWEETS = "GET_MORE_USER_TWEETS";
export const GET_MORE_TWEETS_FOR_AUTH_USER = "GET_MORE_TWEETS_FOR_AUTH_USER";
export const GET_MORE_TWEETS_WHO_YOU_READING =
  "GET_MORE_TWEETS_WHO_YOU_READING";
export const GET_MORE_BOOKMARKS = "GET_MORE_BOOKMARKS";
export const GET_MORE_ANSWERS = "GET_MORE_ANSWERS";
export const GET_MORE_TWEETS_WITH_LIKES = "GET_MORE_TWEETS_WITH_LIKES";
export const GET_MORE_TWEETS_WITH_MEDIA = "GET_MORE_TWEETS_WITH_MEDIA";
export const GET_TWEETS_BY_USER = "GET_TWEETS_BY_USER";
export const GET_PUBLIC_TWEETS_BY_USER = "GET_PUBLIC_TWEETS_BY_USER";
export const GET_MORE_PUBLIC_TWEETS_BY_USER = "GET_MORE_PUBLIC_TWEETS_BY_USER";
export const GET_TWEETS_BY_FOLLOWING_USERS = "GET_TWEETS_BY_FOLLOWING_USERS";
export const GET_FAVORITE_TWEETS = "GET_FAVORITE_TWEETS";
export const GET_TWEETS_FOR_AUTH_USER = "GET_TWEETS_FOR_AUTH_USER";
export const GET_TWEETS_WITH_MEDIA = "GET_TWEETS_WITH_MEDIA";
export const GET_TWEETS_WITH_LIKES = "GET_TWEETS_WITH_LIKES";
export const GET_TWEETS_FOR_TRENDS = "GET_TWEETS_FOR_TRENDS";
export const GET_TWEETS_FOR_TRENDS_AUTH_USER =
  "GET_TWEETS_FOR_TRENDS_AUTH_USER";
export const GET_MORE_TWEETS_FOR_TRENDS = "GET_MORE_TWEETS_FOR_TRENDS";
export const GET_ANSWERS = "GET_ANSWERS";

export const REQUEST_TWEETS_STARTED = "REQUEST_TWEETS_STARTED";
export const REQUEST_TWEETS_FAILED = "REQUEST_TWEETS_FAILED";
export const REQUEST_TWEETS_WHO_YOU_READING_STARTED =
  "REQUEST_TWEETS_WHO_YOU_READING_STARTED";
export const REQUEST_TWEETS_WHO_YOU_READING_FAILED =
  "REQUEST_TWEETS_WHO_YOU_READING_FAILED";
export const REQUEST_USER_TWEETS_STARTED = "REQUEST_USER_TWEETS_STARTED";
export const REQUEST_USER_TWEETS_FAILED = "REQUEST_USER_TWEETS_FAILED";
export const REQUEST_TWEETS_FOR_AUTH_USER_STARTED =
  "REQUEST_TWEETS_FOR_AUTH_USER_STARTED";
export const REQUEST_TWEETS_FOR_AUTH_USER_FAILED =
  "REQUEST_TWEETS_FOR_AUTH_USER_FAILED";
export const REQUEST_TWEETS_WITH_MEDIA_STARTED =
  "REQUEST_TWEETS_WITH_MEDIA_STARTED";
export const REQUEST_TWEETS_WITH_MEDIA_FAILED =
  "REQUEST_TWEETS_WITH_MEDIA_FAILED";
export const REQUEST_TWEETS_WITH_LIKES_STARTED =
  "REQUEST_TWEETS_WITH_LIKES_STARTED";
export const REQUEST_TWEETS_WITH_LIKES_FAILED =
  "REQUEST_TWEETS_WITH_LIKES_FAILED";
export const REQUEST_ANSWERS_STARTED = "REQUEST_ANSWERS_STARTED";
export const REQUEST_ANSWERS_FAILED = "REQUEST_ANSWERS_FAILED";
export const REQUEST_BOOKMARKS_STARTED = "REQUEST_BOOKMARKS_STARTED";
export const REQUEST_BOOKMARKS_FAILED = "REQUEST_BOOKMARKS_FAILED";
export const REQUEST_TWEETS_FOR_TRENDS_STARTED =
  "REQUEST_TWEETS_FOR_TRENDS_STARTED";
export const REQUEST_TWEETS_FOR_TRENDS_FAILED =
  "REQUEST_TWEETS_FOR_TRENDS_FAILED";
